# Generated by Django 3.1.1 on 2020-11-15 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('duration', models.IntegerField(default=3)),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('eas_address', models.IntegerField()),
                ('eas_building', models.IntegerField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='api.area')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('eas_address', models.IntegerField()),
                ('eas_building', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.accident')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='NormalCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normals', to='api.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normals', to='api.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
