# Generated by Django 3.1.1 on 2020-11-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201115_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
