# Generated by Django 3.1.1 on 2020-11-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201115_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalcount',
            name='value',
            field=models.IntegerField(default=-1),
        ),
    ]
