# Generated by Django 3.1.1 on 2020-11-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_normalcount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalcount',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
